### ISSUE TITLE
bot not log in server

### ISSUE THREAD

**Issue by jewelalex** [Zheoni/VotaBot#11]
i get this error

##########################
/root/bot/wb-poll/index.js:12
const helpEmbed = new Discord.RichEmbed()
                  ^

TypeError: Discord.RichEmbed is not a constructor
    at Object.<anonymous> (/root/bot/wb-poll/index.js:12:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

#######################

**Comment by Zheoni** [comment]
Probably you got the wrong discord.js version. I think they changed that in a recent one. I will check what version I am using later today, tell you and fix the package.json

**Comment by jewelalex** [comment]
ok brother

it will be great help for me by the way i didnt change no code just upload like they are with my token only

ill wait

**Comment by Zheoni** [comment]
Hmmm, so I downloaded, the source code, run `npm install` and `node index.js` and it worked for me. I'm using `discord.js` version `11.6.4`. Can you check what version are you using? You can do that by running `npm list` or by looking at the version property in the `node_modules/discord.js/package.json` file.

**Comment by jewelalex** [comment]
yeh i seen its "discord.js@^12.5.1"

**Comment by jewelalex** [comment]
how can i install 11.6.4 as im using this " npm install discord.js --save " to install discord.js

**Comment by Zheoni** [comment]
`cd` into the base path of the project (from your first comment, I think it is `/root/bot/wb-poll/`), then run:
- `npm install discord.js@11.6.4`.

Then you can make sure it is the correct version by checking the package.json file and the `npm list` command.

**Comment by jewelalex** [comment]
do i use "license": "MIT", or ISC

**Comment by jewelalex** [comment]
i have one more request if u have any scheduled announcement code plz or may i can use in same bot

thx

**Comment by Zheoni** [comment]
This project is licensed under an MIT license.

You should not change that, and if npm asked you to do so, maybe you are doing something wrong, make sure to clone all files in the repository and run the instructions in the readme file.

No, I don't have any scheduled announcement code, this bot only makes polls and close them after a specified time and publishing the results or if no time specified when a command is sent.

You can use any of the source code of this project as long as you include a copy of the LICENSE file and a copyright notice.

**Comment by jewelalex** [comment]
do i have to install ant other packge

**Comment by Zheoni** [comment]
No, again, the only thing you have to do to run the bot is

- get the source code `git clone https://github.com/Zheoni/VotaBot.git`
- install the dependencies automatically `npm install`
- edit the `botconfig.json` file
- run the bot with `node index.js`

As this issue is solved and the problem was on your end, I'm closing it. This is not a tutorial on how to use git or npm, this is just to solve problems with this project.
