### ISSUE TITLE
When the bot launches, after a few seconds it shows a error message and stops the bot.

### ISSUE THREAD

**Issue by WolfyUsesGitHub** [Zheoni/VotaBot#13]
Hello im having an issue. when i use the command node "index.js" the bot says that it has started then it shows the following error message: 
Server is online!
/home/runner/VotaBot/node_modules/discord.js/src/client/ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (/home/runner/VotaBot/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/home/runner/VotaBot/node_modules/discord.js/src/structures/Guild.js:307:68)
    at GuildCreateHandler.handle (/home/runner/VotaBot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/home/runner/VotaBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/runner/VotaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/runner/VotaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/runner/VotaBot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/runner/VotaBot/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! votabot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the votabot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-14T09_42_29_326Z-debug.log

I am hosting the bot on repl.it and i have no idea on how node.js works. please someone help me!

**Comment by Zheoni** [comment]
I do not maintain this project anymore. The VotaBot I'm hosting is a totally different codebase. When I make it public (hopefully, soon). This repo will be archived and the new repo will be linked in the readme.

With a quick look at the error message in your issue, I would say either you have the incorrect version of discord.js intalled or discord has stopped supporting the version of this bot. But I can't help you sorry.
